import { Linking, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { colors, spacing } from '@/constants/theme';

export default function PrivacyPolicy() {
  return (
    <ScrollView style={styles.root} contentContainerStyle={styles.content}>
      <View style={styles.header}>
        <Pressable onPress={() => router.canGoBack() ? router.back() : router.replace('/')}
          style={({ pressed }) => [styles.back, pressed && { opacity: 0.7 }]}>
          <Ionicons name="arrow-back" size={16} color={colors.accent} />
          <Text style={styles.backText}>Back</Text>
        </Pressable>
      </View>

      <Text style={styles.h1}>Privacy Policy</Text>
      <Text style={styles.meta}>Qwalla · Last updated: March 30, 2026</Text>

      <Section title="1. Overview">
        Qwalla is a self-custodial, post-quantum secure wallet and messaging application built on the RougeChain blockchain. This policy explains what data we collect, how we use it, and your rights as a user.{'\n\n'}
        Qwalla is designed with a privacy-first architecture: your private keys and seed phrase never leave your device, message content is end-to-end encrypted and unreadable to us, and we do not run advertising networks or sell user data.
      </Section>

      <Section title="2. Information We Collect">
        <Bold>Data you provide:</Bold>{'\n'}
        • Wallet public key — stored on-chain (public){'\n'}
        • Display name (optional) — stored on-chain (public){'\n'}
        • Mail name / address (optional) — stored on-chain (public){'\n'}
        • NFT avatar selection — stored on your device only{'\n'}
        • Wallet password / passphrase — stored on your device only (encrypted){'\n\n'}
        <Bold>Data generated by your activity:</Bold>{'\n'}
        • Transactions — permanently recorded on the RougeChain public ledger{'\n'}
        • NFT ownership — publicly visible on-chain{'\n'}
        • Push notification token — registered with the RougeChain API to deliver alerts (does not identify you by name){'\n\n'}
        <Bold>Data we do NOT collect:</Bold>{'\n'}
        • Private keys or seed phrase — generated and stored exclusively on your device, never transmitted{'\n'}
        • Message or mail content — end-to-end encrypted with ML-KEM-768, unreadable to us{'\n'}
        • Location data{'\n'}
        • Device identifiers, advertising IDs, or behavioral analytics
      </Section>

      <Section title="3. Camera Permission">
        Qwalla requests camera access solely to scan QR codes for connecting to dApps or pairing wallet sessions. No images are captured, stored, or transmitted.
      </Section>

      <Section title="4. Third-Party Services">
        • RougeChain Network — all on-chain interactions{'\n'}
        • Expo Push Notifications (Expo, Inc.) — delivers push alerts to your device{'\n'}
        • IPFS / ipfs.io — resolves NFT metadata images directly from your device{'\n'}
        • Base Sepolia Bridge — used only if you bridge ETH or USDC cross-chain{'\n\n'}
        We do not share your data with any advertising networks, data brokers, or analytics providers.
      </Section>

      <Section title="5. Blockchain Data and Permanence">
        Because RougeChain is a public, decentralized blockchain, data written on-chain is public and permanent. This includes your wallet address, transaction history, NFT holdings, registered names, and any other data you submit to the network. We have no ability to delete or modify on-chain data on your behalf.
      </Section>

      <Section title="6. Data Security">
        • Private keys and seed phrase are stored using your device's secure enclave via expo-secure-store{'\n'}
        • You may optionally protect your wallet with an additional passphrase{'\n'}
        • The wallet auto-locks when the app is backgrounded{'\n'}
        • All message and mail content is encrypted end-to-end with post-quantum cryptography (ML-KEM-768 / ML-DSA-65) before transmission
      </Section>

      <Section title="7. Children's Privacy">
        Qwalla is not directed at children under 13. We do not knowingly collect any personal information from children. If you believe a child has provided us with personal information, please contact us and we will take steps to delete it.
      </Section>

      <Section title="8. Changes to This Policy">
        We may update this policy from time to time. When we do, we will revise the "Last updated" date at the top of this page. Continued use of the app after changes constitutes acceptance of the updated policy.
      </Section>

      <Section title="9. Your Rights (EEA / UK / California)">
        Depending on where you live, you may have rights including:{'\n'}
        • Access: Request a copy of personal data we hold about you{'\n'}
        • Deletion: Request deletion of personal data we hold (note: on-chain data cannot be deleted){'\n'}
        • Portability: Export your wallet using the encrypted backup feature in Settings{'\n'}
        • Opt-out of notifications: Revoke notification permissions at any time in your device settings
      </Section>

      <Section title="10. Contact">
        If you have questions about this privacy policy or your data:{'\n\n'}
        <Pressable onPress={() => Linking.openURL('mailto:admin@qwallo.io')}>
          <Text style={styles.link}>admin@qwallo.io</Text>
        </Pressable>
      </Section>

      <View style={styles.footer}>
        <Pressable onPress={() => router.replace('/')}
          style={({ pressed }) => [pressed && { opacity: 0.7 }]}>
          <Text style={styles.footerLink}>qwalla.io</Text>
        </Pressable>
        <Text style={styles.footerSep}>·</Text>
        <Pressable onPress={() => router.replace('/terms')}
          style={({ pressed }) => [pressed && { opacity: 0.7 }]}>
          <Text style={styles.footerLink}>Terms of Service</Text>
        </Pressable>
      </View>
    </ScrollView>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <View style={styles.section}>
      <Text style={styles.h2}>{title}</Text>
      <Text style={styles.body}>{children}</Text>
    </View>
  );
}

function Bold({ children }: { children: React.ReactNode }) {
  return <Text style={styles.bold}>{children}</Text>;
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bg },
  content: { maxWidth: 740, alignSelf: 'center', width: '100%', padding: spacing.lg, paddingBottom: 64 },
  header: { marginBottom: spacing.lg },
  back: { flexDirection: 'row', alignItems: 'center', gap: 6, alignSelf: 'flex-start' },
  backText: { color: colors.accent, fontSize: 14, fontWeight: '600' },
  h1: { color: colors.text, fontSize: 32, fontWeight: '800', letterSpacing: -0.5, marginBottom: 8 },
  meta: { color: colors.textTertiary, fontSize: 13, marginBottom: spacing.xl },
  section: { marginBottom: spacing.xl },
  h2: { color: colors.text, fontSize: 17, fontWeight: '700', marginBottom: spacing.sm },
  body: { color: colors.textSecondary, fontSize: 15, lineHeight: 26 },
  bold: { color: colors.text, fontWeight: '700' },
  link: { color: colors.accent, fontSize: 15, textDecorationLine: 'underline' },
  footer: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: spacing.xl, paddingTop: spacing.lg, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.border },
  footerLink: { color: colors.textSecondary, fontSize: 13, textDecorationLine: 'underline' },
  footerSep: { color: colors.textTertiary, fontSize: 13 },
});
